---
- name: Setup Network
  hosts: localhost
  gather_facts: false
  #vars_files: configs.yml
  collections:
    - nutanix.ncp

  tasks:
  - name: Create external subnet with NAT
    ntnx_subnets:
      state: present
      nutanix_host: 10.44.76.88
      nutanix_username: admin
      nutanix_password: Nutanix.123
      validate_certs: false
      name: AZ01-NAT
      external_subnet:
        vlan_id: 102
        cluster:
          name: auto_cluster_prod_1a642ea0a5c3
        enable_nat: true
        ipam:
          network_ip: 10.44.3.192
          network_prefix: 27
          gateway_ip: 10.44.3.193
          ip_pools:
            - start_ip: 10.44.3.198
              end_ip: 10.44.3.207

  - name: Create external subnet without nat
    ntnx_subnets:
      state: present
      nutanix_host: 10.44.76.88
      nutanix_username: admin
      nutanix_password: Nutanix.123
      validate_certs: false
      name: AZ01-No-NAT
      external_subnet:
        vlan_id: 103 #102
        cluster:
          name: auto_cluster_prod_1a642ea0a5c3
        enable_nat: False
        ipam:
          network_ip: 10.44.3.192
          network_prefix: 27
          gateway_ip: 10.44.3.193
          ip_pools:
            - start_ip: 10.44.3.198
              end_ip: 10.44.3.207
 

  - name: create VPC and connect it to external subnet 1
    ntnx_vpcs:
        validate_certs: False
        state: present
        nutanix_host: "10.44.76.88"
        nutanix_username: "admin"
        nutanix_password: "Nutanix.123"
        name: MinVPC-nat
        external_subnets:
          - subnet_name: AZ01-NAT
  
  - name: create VPC and connect it to external subnet 2
    ntnx_vpcs:
        validate_certs: False
        state: present
        nutanix_host: "10.44.76.88"
        nutanix_username: "admin"
        nutanix_password: "Nutanix.123"
        name: MinVPC-no-nat
        external_subnets:
          - subnet_name: AZ01-No-NAT

  - name: Overlay Subnet with external nat
    ntnx_subnets:
      state: present
      nutanix_host: "10.44.76.88"
      validate_certs: false
      nutanix_username: admin
      nutanix_password: Nutanix.123
      name: Overlay-Subnet-vpc1
      overlay_subnet:
        vpc:
          name: MinVPC-nat
        ipam:
          network_ip: 10.10.1.0
          network_prefix: 16
          gateway_ip: 10.10.1.1
          ip_pools:
              - start_ip: 10.10.1.50
                end_ip: 10.10.1.100
          dhcp:
              dns_servers:
                - 8.8.8.8
                - 8.8.8.4
              domain_name: "calm.nutanix.com"
              domain_search:
                - calm.nutanix.com
                - eng.nutanix.com
  

  - name: Overlay Subnet w
    ntnx_subnets:
      state: present
      nutanix_host: "10.44.76.88"
      validate_certs: false
      nutanix_username: admin
      nutanix_password: Nutanix.123
      name: Overlay-Subnet-vpc2
      overlay_subnet:
        vpc:
          name: MinVPC-no-nat
        ipam:
          network_ip: 10.20.1.1
          network_prefix: 16
          gateway_ip: 10.20.1.2
          ip_pools:
              - start_ip: 10.20.1.50
                end_ip: 10.20.1.100
          dhcp:
              dns_servers:
                - 8.8.8.8
                - 8.8.8.4
              domain_name: "calm.nutanix.com"
              domain_search:
                - calm.nutanix.com
                - eng.nutanix.com
  - name: vm1
    ntnx_vms:
            state: present
            nutanix_host: "10.44.76.88"
            validate_certs: False
            nutanix_username: admin
            nutanix_password: Nutanix.123
            name: "vm-overlay-vpc1"
            desc: "ansible_vm_description"
            cluster:
              name: auto_cluster_prod_1a642ea0a5c3
            networks:
              - is_connected: True
                subnet:
                  name: Overlay-Subnet-vpc1
  - name: vm2
    ntnx_vms:
          state: present
          nutanix_host: "10.44.76.88"
          validate_certs: False
          nutanix_username: admin
          nutanix_password: Nutanix.123
          name: "vm-overlay-vpc2"
          desc: "ansible_vm_description"
          cluster:
            name: auto_cluster_prod_1a642ea0a5c3
          networks:
            - is_connected: True
              subnet:
                name: Overlay-Subnet-vpc2