---
- name: Policy based routing - NACLs
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  vars:
      nutanix_host: 10.44.76.88
      nutanix_username: admin
      nutanix_password: Nutanix.123
      validate_certs: false
  module_defaults:
    
    ntnx_pbrs:
      nutanix_host: '{{ nutanix_host }}'
      nutanix_username: '{{ nutanix_username }}'
      nutanix_password: '{{ nutanix_password }}'
      validate_certs: '{{ validate_certs }}'
  ignore_errors: true
  tasks:
    - name: Include PBR  task
      include_tasks: pbr.yml
      with_items:
        - { vpc_name: Prod, priority: 101, nip: 10.1.2.0, prefix: 24 }
        - { vpc_name: Dev, priority: 101, nip: 10.1.2.0, prefix: 24 }